SELECT * FROM (
SELECT COUNTRY_ISO_CODE, COUNTRY_NAME, SUM(AMOUNT_SOLD) AS SALES$
FROM (
    SELECT S.CUST_ID, AMOUNT_SOLD, COUNTRY_ISO_CODE, COUNTRY_NAME
    FROM SH.SALES S, SH.CUSTOMERS CUS, SH.COUNTRIES COU, SH.TIMES TIM
    WHERE S.CUST_ID=CUS.CUST_ID 
    	AND CUS.COUNTRY_ID=COU.COUNTRY_ID
    	AND TIM.TIME_ID=S.TIME_ID
    	AND (TIM.CALENDAR_YEAR=1999 OR TIM.CALENDAR_YEAR=2000)
)
GROUP BY COUNTRY_ISO_CODE, COUNTRY_NAME
ORDER BY SALES$)
WHERE ROWNUM<=5;


SELECT PROD_CATEGORY, CALENDAR_MONTH, SUM(AMOUNT_SOLD)
FROM (
    SELECT PROD_CATEGORY, CALENDAR_MONTH_NAME AS CALENDAR_MONTH, AMOUNT_SOLD
    FROM SH.SALES S, SH.PRODUCTS PRO, SH.TIMES TIM
    WHERE S.PROD_ID=PRO.PROD_ID
    	AND S.TIME_ID=TIM.TIME_ID
    	AND TIM.CALENDAR_YEAR=1999
    	AND TIM.CALENDAR_QUARTER_NUMBER=1
)
GROUP BY CALENDAR_MONTH,PROD_CATEGORY
ORDER BY CALENDAR_MONTH;


SELECT PROD_CATEGORY, CALENDAR_YEAR, PROMO_CATEGORY, SUM(AMOUNT_SOLD) AS SALE_QTY
FROM SH.PRODUCTS PROD, SH.SALES S, SH.PROMOTIONS PROM, SH.TIMES TIM
WHERE PROD.PROD_ID = S.PROD_ID 
AND S.PROMO_ID = PROM.PROMO_ID 
AND S.TIME_ID = TIM.TIME_ID 
AND NVL(PROM.PROMO_CATEGORY,'NO PROMOTION') NOT LIKE 'NO PROMOTION'
GROUP BY ROLLUP(PROD_CATEGORY, CALENDAR_YEAR, PROMO_CATEGORY);


SELECT PROD_CATEGORY, CALENDAR_YEAR, PROMO_CATEGORY, SUM(AMOUNT_SOLD) AS SALE_QTY
FROM SH.PRODUCTS PROD, SH.SALES S, SH.PROMOTIONS PROM, SH.TIMES TIM
WHERE PROD.PROD_ID = S.PROD_ID 
AND S.PROMO_ID = PROM.PROMO_ID 
AND S.TIME_ID = TIM.TIME_ID 
AND NVL(PROM.PROMO_CATEGORY,'NO PROMOTION') NOT LIKE 'NO PROMOTION'
GROUP BY CUBE(PROD_CATEGORY, CALENDAR_YEAR, PROMO_CATEGORY);


CREATE MATERIALIZED VIEW PROMOTION_ANALYSIS_MV
BUILD IMMEDIATE 
REFRESH FORCE
AS
SELECT S.PROMO_ID AS PROMO_ID, PROD.PROD_ID AS  PROD_ID, SUM(S.QUANTITY_SOLD) AS TOTAL_SALES
FROM SH.PRODUCTS PROD
LEFT JOIN SH.SALES S
ON PROD.PROD_ID = S.PROD_ID
GROUP BY PROD.PROD_ID, S.PROMO_ID;


SELECT FW.PROD_SUBCATEGORY,CH.CHANNEL_CLASS, SUM(DOLLARS) AS TOTAL_DOLLARS
FROM SH.FWEEK_PSCAT_SALES_MV FW
LEFT JOIN SH.CHANNELS CH
ON FW.CHANNEL_ID=CH.CHANNEL_ID
GROUP BY ROLLUP(CH.CHANNEL_CLASS, FW.PROD_SUBCATEGORY)
ORDER BY FW.PROD_SUBCATEGORY;
